### PR TITLE
ENTESB-5904 - Moved jmx.acl.whitelist.properties from default profile…

### PR DESCRIPTION
**Pull request by paoloantinori**
… in Fuse repo to acls profile in Fabric8 repo

### CODE REVIEW

**Comment by paoloantinori** [comment]
has a companion PR here: https://github.com/jboss-fuse/fabric8/pull/748

**Comment by kevinearls** [comment]
ok to test

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
Same situation here?

**Comment by tadayosi** [comment]
Yeah, but probably it's ok. The `master` branch isn't used any more and the build has been failing for some other reasons for quite long time.

**Pull request merged**
