### PR TITLE
[ENTESB-5803] Update patch-management bundle

### PR DESCRIPTION
**Pull request by grgrzybek**
@janstey Please merge just before next perfectus

### CODE REVIEW

**Comment by grgrzybek** [comment]
don't merge yet!

**Comment by janstey** [comment]
Gonna try merging because perfectus failed in related area :-)

**Comment by janstey** [comment]
Had to merge manually because perfectus already updated branch to new versions... lets see how it goes...

**Comment by grgrzybek** [comment]
Yes - sorry - I didn't know we're starting perfectus ;)

cheers
Grzegorz

2016-07-22 1:54 GMT+02:00 Jonathan Anstey <notifications@github.com>:

**Pull request merged**
