### PR TITLE
OSFUSE-62: ENTESB-6022: Changed kar dependencies to provided scope

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by janstey** [comment]
ok to test

**Comment by sjavurek** [comment]
Please retest

**Comment by dhirajsb** [comment]
@kevinearls ,looks like you had to abort the build. What was the reason? I don't see any failed tests.

**Comment by apupier** [comment]
@dhirajsb it seems that the build was stuck "Aborted	#213	8 hr 10 min"

**Comment by kevinearls** [comment]
ok to test

**Comment by kevinearls** [comment]
retest this please

**Comment by kevinearls** [comment]
Hi @dhirajsb @apupier is correct, I killed this after Lars notified me that it was hung.  We were having some issues with Jenkins slaves that week, so it's possible it hung because of that.  Unfortunately for some reason I've not been able to get Jenkins to rerun it.  Could you delete this PR and submit a new one?

**Comment by dhirajsb** [comment]
Aborting PR to open a new one instead.

**Pull request closed without merging**
